pythonCourse/courses/urls.py
from django.urls import path

from .views import *

app_name = 'courses'
urlpatterns = [
    path('home/', home, name='home'),
    path('topic/<int:pk>/', topic, name='topic'),
    path('topic/<int:pk>/update/', topicUpdate, name='topicUpdate'),
    path('topic/<int:topic_id>/content/<int:pk>/', content, name='content'),
    path('topic/<int:topic_id>/content/<int:pk>/update/', contentUpdate, name='contentUpdate'),
    path('topic/<int:topic_id>/content/<int:content_id>/contentPart/<int:pk>/update/', contentPartUpdate, name='contentPartUpdate'),
    path('create/', create, name='create'),
    path('createTopic/', createTopic, name='createTopic'),
    path('createContent/', createContent, name='createContent'),
    path('createContentPart/', createContentPart, name='createContentPart'),
]

pythonCourse/pythonCourse/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import *

urlpatterns = [
    path('', index, name='index'),
    path('accounts/signup/', SignupView.as_view(), name='signup'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('courses/', include('courses.urls')),
]

pythonCourse/courses/models.py
from django.db.models import (CASCADE, CharField, DateTimeField, ForeignKey,
                              Model, TextField, IntegerField)

from .utils.dateUtils import *


class Topic(Model):
    name = CharField(max_length=50)
    created_by = CharField(max_length=50)
    creation_date = DateTimeField(auto_now_add=True)
    last_update_user = CharField(max_length=50)
    last_update = DateTimeField()

    def __str__(self) -> str:
        return "{}".format(self.name)

    def creation_date_info(self):
        return creation_or_update_date_info(self.creation_date, None, self.created_by)

    def update_date_info(self):
        return creation_or_update_date_info(None, self.last_update, self.last_update_user)


class Content(Model):
    '''
        Content in a Topic
        Can be seen as a chapter
    '''
    topic = ForeignKey(Topic, on_delete=CASCADE)
    name = CharField(max_length=50)
    description = TextField()
    created_by = CharField(max_length=50)
    creation_date = DateTimeField(auto_now_add=True)
    last_update_user = CharField(max_length=50)
    last_update = DateTimeField()

    def __str__(self) -> str:
        return "{}".format(self.name)

    def creation_date_info(self):
        return creation_or_update_date_info(self.creation_date, None, self.created_by)

    def update_date_info(self):
        return creation_or_update_date_info(None, self.last_update, self.last_update_user)


class ContentType(Model):
    '''
        Type of a content part
        Can be text/code/...
    '''
    name = CharField(max_length=50)
    description = CharField(max_length=200)

    def __str__(self) -> str:
        return "{}".format(self.name)


class ContentPart(Model):
    '''
        ContentPart in a Content
        Can be seen as a section
            section_number reflects the order the content part is displayed
    '''
    content = ForeignKey(Content, on_delete=CASCADE)
    type = ForeignKey(ContentType, on_delete=CASCADE)
    section_number = IntegerField()
    title = CharField(max_length=150)
    text = TextField()
    created_by = CharField(max_length=50)
    creation_date = DateTimeField(auto_now_add=True)
    last_update_user = CharField(max_length=50)
    last_update = DateTimeField()

    def __str__(self) -> str:
        return "Content Part nº{}".format(self.section_number)

    def creation_date_info(self):
        return creation_or_update_date_info(self.creation_date, None, self.created_by)

    def update_date_info(self):
        return creation_or_update_date_info(None, self.last_update, self.last_update_user)

pythonCourse/courses/forms.py
from django.forms import *
from .models import Topic, Content, ContentPart


class TopicForm(ModelForm):

    class Meta:
        model = Topic
        fields = ["name", "created_by", "last_update_user", "last_update",]
        labels = {
            "name": "Name",
            "created_by": "Created By",
        }
        widgets = {
            "created_by": HiddenInput(),
            "last_update_user": HiddenInput(),
            "last_update": HiddenInput(),
        }


class ContentForm(ModelForm):

    class Meta:
        model = Content
        fields = ["name", "description", "topic", "created_by",]
        labels = {
            "name": "Name",
            "topic": "Topic",
            "description": "Description",
            "created_by": "Created By",
        }
        widgets = {
            "description": Textarea(attrs={'rows': 2}),
            'created_by': HiddenInput()
        }


class ContentListForm(ModelForm):
    class Meta:
        model = Content
        fields = ["topic",]
        labels = {
            "topic": "Topic",
        }
        widgets = {'topic': Select(attrs={'onChange': 'submit();'})}


class ContentPartForm(ModelForm):

    class Meta:
        model = ContentPart
        fields = ["title", "content", "type", "text", "created_by"]
        labels = {
            "title": "Title",
            "content": "Content",
            "type": "Type",
            "text": "Content",
            "created_by": "Created By",
        }
        widgets = {
            "text": Textarea(attrs={'rows': 2}),
            "created_by": HiddenInput(),
        }


class ContentPartListForm(ModelForm):
    class Meta:
        model = ContentPart
        fields = ["content",]
        labels = {
            "content": "Content",
        }
        widgets = {'content': Select(attrs={'onChange': 'submit();'})}

pythonCourse/courses/views.py
from django.shortcuts import render
from django.http import Http404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user

from .models import *
from .forms import *
from .utils.dictUtils import *

base_context: dict = {
    'topic_list': Topic.objects.all(),
}

# Basic screens


@login_required
def home(request):
    return render(request, 'courses/home.html', base_context)


def navbar(request):
    return render(request, 'courses/navbar.html', base_context)


@login_required
def topic(request, pk):
    try:
        topic = Topic.objects.get(pk=pk)
        content_list = Content.objects.filter(topic=topic)
    except Topic.DoesNotExist:
        raise Http404("Topic doesn't exists")
    context: dict = {
        'content_list': content_list,
        'topic': topic,
    }
    return render(request, 'courses/topic.html',  merge(base_context, context))


@login_required
def content(request, topic_id, pk):
    try:
        content = Content.objects.get(pk=pk)
        content_part_list = ContentPart.objects.filter(
            content=content).order_by('section_number')
        topic = Topic.objects.get(pk=topic_id)
        content_list = Content.objects.filter(topic=topic)
    except Content.DoesNotExist:
        raise Http404("Content doesn't exists")
    context = {
        'content': content,
        'content_list': content_list,
        'content_parts': content_part_list,
    }
    return render(request, 'courses/content.html', merge(base_context, context))

# Create screens


@login_required
def create(request):

    content_list = []
    content_part_list = []

    if request.method == "GET":
        form = ContentListForm(request.GET)
        selected_topic = request.GET.get("topic")
        content_list = Content.objects.all().filter(topic=selected_topic)
    else:
        form = ContentListForm()

    if request.method == "GET":
        form2 = ContentListForm(request.GET)
        selected_topic = request.GET.get("topic")
        content_list = Content.objects.all().filter(topic=selected_topic)
    else:
        form2 = ContentListForm()

    if request.method == "GET":
        form3 = ContentPartListForm(request.GET)
        selected_content = request.GET.get("content")
        content_part_list = ContentPart.objects.all().filter(content=selected_content)
    else:
        form3 = ContentListForm()

    context: dict = {
        'form': form,
        'form2': form2,
        'form3': form3,
        'content_list': content_list,
        'content_part_list': content_part_list,
    }
    return render(request, 'courses/create.html', merge(base_context, context))


@login_required
def createTopic(request):
    if request.method == "POST":
        form = TopicForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        username = get_user(request).get_username()
        form = TopicForm(initial={'created_by': username})

    context = {
        'form': form,
    }

    return render(request, 'courses/createTopic.html', merge(base_context, context))


@login_required
def createContent(request):
    if request.method == "POST":
        form = ContentForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        username = get_user(request).get_username()
        form = ContentForm(initial={'created_by': username})

    content_list = []

    if request.method == "GET":
        form2 = ContentListForm(request.GET)
        selected_topic = request.GET.get("topic")
        content_list = Content.objects.all().filter(topic=selected_topic)
    else:
        form2 = ContentListForm()

    context = {
        'form': form,
        'form2': form2,
        'content_list': content_list,
    }

    return render(request, 'courses/createContent.html', merge(base_context, context))


@login_required
def createContentPart(request):
    cp = ContentPart()
    if request.method == "POST":
        form = ContentPartForm(request.POST, instance=cp)
        if form.is_valid():
            content_parts = ContentPart.objects.all().filter(
                content=form.data["content"])
            order = len(content_parts) + 1
            new_part = form.save(commit=False)
            new_part.section_number = order
            new_part.save()
            form.save_m2m()
    else:
        username = get_user(request).get_username()
        form = ContentPartForm(initial={'created_by': username})

    content_part_list = []

    if request.method == "GET":
        form2 = ContentPartListForm(request.GET)
        selected_content = request.GET.get("content")
        content_part_list = ContentPart.objects.all().filter(content=selected_content)
    else:
        form2 = ContentListForm()

    context = {
        'form': form,
        'form2': form2,
        'content_part_list': content_part_list,
    }

    return render(request, 'courses/createContentPart.html', merge(base_context, context))


# Update screens
def topicUpdate(request, pk):

    topic = Topic.objects.get(id=pk)

    if request.method == "POST":
        form = TopicForm(request.POST, instance=topic)
        if form.is_valid():
            form.save()
    else:
        username = get_user(request).get_username()
        form = TopicForm(
            initial={
                'last_update_user': username,
                'last_update': timezone.now
            },
            instance=topic
        )

    context = {
        'form': form,
        'topic': topic,
    }

    return render(request, "courses/updateTopic.html", merge(base_context, context))


def contentUpdate(request, topic_id, pk):

    content = Content.objects.get(id=pk)

    if request.method == "POST":
        form = ContentForm(request.POST, instance=content)
        if form.is_valid():
            form.save()
    else:
        username = get_user(request).get_username()
        form = ContentForm(
            initial={
                'last_update_user': username,
                'last_update': timezone.now
            },
            instance=content
        )

    context = {
        'form': form,
        'topic': content,
    }

    return render(request, "courses/updateContent.html", merge(base_context, context))


def contentPartUpdate(request, topic_id, content_id, pk):
    pass

pythonCourse/courses/templates/courses/content.html
{% extends "base.html" %}
{% block csshead %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'courses/css/content.css' %}"/>
{% endblock %}
{% load crispy_forms_tags %}
{% block title %}Content{% endblock %}
{% block content %}
  <div class="contentWrapper">
    <h1 class="head"
        title="{{ content.creation_date_info }} | {{ content.update_date_info }}">{{ content.name }}</h1>
    <div class="content">
      {% if content_parts %}
        <ul>
          {% for content_part in content_parts %}
            <li>
              <h5 class="subtitle"
                  title="{{ content_part.creation_date_info }} | {{ content_part.update_date_info }}">
                {{ content_part.title }}
              </h5>
              <div>
                {% if content_part.type_id == 2 %}
                  <code class="code">
                    {{ content_part.text|linenumbers|linebreaks }}
                  </code>
                {% elif content_part.type_id == 3 %}
                  <div class="note">
                    <p>{{ content_part.text|linebreaks }}</p>
                  </div>
                {% else %}
                  <div class="text">
                    <p>{{ content_part.text|linebreaks }}</p>
                  </div>
                {% endif %}
              </div>
              <br/>
            </li>
          {% endfor %}
        </ul>
      {% else %}
        <p>No Content Part available</p>
      {% endif %}
    </div>
    <div class="list">
      <h5 class="subtitle">{{ content.topic.name }}:</h5>
      {% if content_list %}
        <ul>
          {% for content in content_list %}
            <li>
              <a href="{% url 'courses:content' content.topic.id content.id %}">{{ content.name }}</a>
            </li>
          {% endfor %}
        </ul>
      {% else %}
        <p>No Content available</p>
      {% endif %}
    </div>
  </div>
{% endblock %}

pythonCourse/courses/templates/courses/create.html
{% extends "base.html" %}
{% block csshead %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'courses/css/createScreen.css' %}"/>
{% endblock %}
{% load crispy_forms_tags %}
{% block title %}Resources{% endblock %}
{% block content %}
  <div class="createWrapper">
    <h1 class="head">Manage Python Course Resources</h1>
    <div class="topic">
      <h4 class="head">Topics</h4>
      <div class="create">
        <a href="{% url 'courses:createTopic' %}" class="subtitle">Create a Topic</a>
      </div>
      <h6 class="update subtitle">Update:</h6>
      <div class="list">
        {% if topic_list %}
          <ul>
            {% for topic in topic_list %}
              <li>
                <a href="{% url 'courses:topicUpdate' topic.id %}">{{ topic.name }}</a>
              </li>
            {% endfor %}
          </ul>
        {% else %}
          <p>No topic created yet</p>
        {% endif %}
      </div>
    </div>
    <div class="content">
      <h4 class="head">Contents</h4>
      <div class="create">
        <a href="{% url 'courses:createContent' %}" class="subtitle">Create a Content</a>
      </div>
      <h6 class="update subtitle">Update:</h6>
      <div class="formList">
        <form method="get">
          {% csrf_token %}
          {{ form|crispy }}
        </form>
      </div>
      <div class="list">
        {% if content_list %}
          <ul>
            {% for content in content_list %}
              <li>
                <a href="{% url 'courses:contentUpdate' content.topic.id content.id %}">{{ content.name }}</a>
              </li>
            {% endfor %}
          </ul>
        {% else %}
          <p>No Content created yet</p>
        {% endif %}
      </div>
    </div>
    <div class="contentPart">
      <h4 class="head">Content Parts</h4>
      <div class="create">
        <a href="{% url 'courses:createContentPart' %}" class="subtitle">Create a Content Part</a>
      </div>
      <h6 class="update subtitle">Update:</h6>
      <div class="formList">
        <form method="get">
          {% csrf_token %}
          {{ form2|crispy }}
        </form>
        {% if content_list %}
          <form method="get">
            {% csrf_token %}
            {{ form3|crispy }}
          </form>
        {% endif %}
      </div>
      <div class="list">
        {% if content_part_list %}
          <ul>
            {% for content_part in content_part_list %}
              <li>
                <a href="{% url 'courses:contentPartUpdate' content_part.content.topic.id content_part.content.id content_part.id %}">{{ content_part.title }}</a>
              </li>
            {% endfor %}
          </ul>
        {% else %}
          <p>No Content Part created yet</p>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

pythonCourse/courses/templates/courses/createContent.html
{% extends "base.html" %}
{% block csshead %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'courses/css/createScreen.css' %}"/>
{% endblock %}
{% load crispy_forms_tags %}
{% block title %}Create Contents{%  endblock %}
{% block content %}
  <div class="createScreenWrapper">
    <div class="head">
      <h1>Create some Contents</h1>
    </div>
    <div class="form">
      <form action="{% url 'courses:createContent' %}" method="post">
        <fieldset>
          <legend>
            <h5>Create a Content</h5>
          </legend>
          {% csrf_token %}
          {{ form|crispy }}
        </fieldset>
        <div class="button">
          <button type="submit" class="btn">Create</button>
        </div>
      </form>
    </div>
    <div class="list">
      <h5>Content List</h5>
      <form method="get" id="contents-form">
        {% csrf_token %}
        {{ form2|crispy }}
      </form>
      {% if content_list %}
        <ul>
          {% for content in content_list %}
            <li>
              <a href="{% url 'courses:content' content.topic.id content.id %}">{{ content.name }}</a>
            </li>
          {% endfor %}
        </ul>
      {% else %}
        <p>No Content related to selected Topic has been created yet</p>
      {% endif %}
    </div>
  </div>
{% endblock %}

pythonCourse/courses/templates/courses/createContentPart.html
{% extends "base.html" %}
{% block csshead %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'courses/css/createScreen.css' %}"/>
{% endblock %}
{% load crispy_forms_tags %}
{% block title %}Create Content Parts{%  endblock %}
{% block content %}
  <div class="createScreenWrapper">
    <div class="head">
      <h1>Create some Content Parts</h1>
    </div>
    <div class="form">
      <form action="{% url 'courses:createContentPart' %}" method="post">
        <fieldset>
          <legend>
            <h5>Create a Content Part</h5>
          </legend>
          {% csrf_token %}
          {{ form|crispy }}
        </fieldset>
        <div class="button">
          <button type="submit" class="btn">Create</button>
        </div>
      </form>
    </div>
    <div class="list">
      <h5>Content Part List</h5>
      <form method="get">
        {% csrf_token %}
        {{ form2|crispy }}
      </form>
      {% if content_part_list %}
        <ul>
          {% for content_part in content_part_list %}
            <li>
              <a href="{% url 'courses:content' content_part.content.topic.id content_part.content.id %}">{{ content_part.section_number }}: {{ content_part.title }}</a>
            </li>
          {% endfor %}
        </ul>
      {% else %}
        <p>No Content related to selected Topic has been created yet</p>
      {% endif %}
    </div>
  </div>
{% endblock %}

pythonCourse/courses/templates/courses/createTopic.html
{% extends "base.html" %}
{% block csshead %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'courses/css/createScreen.css' %}"/>
{% endblock %}
{% load crispy_forms_tags %}
{% block title %}Create Topics{% endblock %}
{% block content %}
  <div class="createScreenWrapper">
    <h1 class="head">Create some Topics</h1>
    <div class="form">
      <form action="{% url 'courses:createTopic' %}" method="post">
        <fieldset>
          <legend>
            <h5>Create a Topic</h5>
          </legend>
          {% csrf_token %}
          {{ form|crispy }}
        </fieldset>
        <div class="button">
          <button type="submit" class="btn">Create</button>
        </div>
      </form>
    </div>
    <div class="list">
      <h5>Topic List</h5>
      {% if topic_list %}
        <ul>
          {% for topic in topic_list %}
            <li>
              <a href="{% url 'courses:topic' topic.id %}">{{ topic.name }}</a>
            </li>
          {% endfor %}
        </ul>
      {% else %}
        <p>No topic created yet</p>
      {% endif %}
    </div>
  </div>
{% endblock %}

pythonCourse/courses/templates/courses/home.html
{% extends "base.html" %}
{% block csshead %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'courses/css/home.css' %}"/>
{% endblock %}
{% block title %}Home{% endblock %}
{% block content %}
    <div class="homeScreenWrapper">
        <h1 class="head">Hello ! Welcome to Python Courses.</h1>
        <div class="img">
            <img src="{% static 'courses/img/python_logo.png' %}"
                 alt="Python Logo"
                 width="200"
                 height="200"/>
        </div>
    </div>
{% endblock %}

pythonCourse/courses/templates/courses/navbar.html
{% block csshead %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'courses/css/style.css' %}"/>
{% endblock %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'courses:home' %}">Python Courses</a>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'courses:home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle"
           href="#"
           id="topicDropdown"
           role="button"
           data-toggle="dropdown"
           aria-haspopup="true"
           aria-expanded="false">
          Topics
        </a>
        <div class="dropdown-menu bg-dark" aria-labelledby="topicDropdown">
          {% for topic in topic_list %}
            <a class="dropdown-item" href="{% url 'courses:topic' topic.id %}">{{ topic.name }}</a>
          {% endfor %}
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'courses:create' %}">Resources</a>
      </li>
    </ul>
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle"
           href="#"
           id="shutdownDropdown"
           role="button"
           data-toggle="dropdown"
           aria-haspopup="true"
           aria-expanded="false">
          <img src="{% static 'courses/img/power-button.png' %}"
               alt="Log Out"
               width="20"
               height="20"/>
        </a>
        <div class="dropdown-menu bg-dark dropdown-menu-right"
             aria-labelledby="shutdownDropdown">
          <a class="dropdown-item" href="#">Profile</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="/accounts/logout">Log Out</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

pythonCourse/courses/templates/courses/topic.html
{% extends "base.html" %}
{% block csshead %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'courses/css/topic.css' %}"/>
{% endblock %}
{% load crispy_forms_tags %}
{% block title %}Topic{% endblock %}
{% block content %}
    <div class="topicWrapper">
        <div class="head">
            <h3 title="{{ topic.creation_date_info }} | {{ topic.update_date_info }}">{{ topic.name }}</h3>
        </div>
        <div class="list">
            <h4>Content List</h4>
            {% if content_list %}
                <ul>
                    {% for content in content_list %}
                        <li>
                            <a href="{% url 'courses:content' content.topic.id content.id %}">{{ content.name }}</a>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>No Content available</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

pythonCourse/courses/templates/courses/updateTopic.html
{% extends "base.html" %}
{% block csshead %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'courses/css/createScreen.css' %}"/>
{% endblock %}
{% load crispy_forms_tags %}
{% block title %}Create Topics{% endblock %}
{% block content %}
  <div class="createScreenWrapper">
    <h1 class="head">Update some Topics</h1>
    <div class="form">
      <form action="{% url 'courses:topicUpdate' topic.id %}" method="post">
        <fieldset>
          <legend>
            <h5>Update a Topic</h5>
          </legend>
          {% csrf_token %}
          {{ form|crispy }}
        </fieldset>
        <div class="button">
          <button type="submit" class="btn">Update</button>
        </div>
      </form>
    </div>
    <div class="list">
      <h5>Update other Topics</h5>
      {% if topic_list %}
        <ul>
          {% for topic in topic_list %}
            <li>
              <a href="{% url 'courses:topicUpdate' topic.id %}">{{ topic.name }}</a>
            </li>
          {% endfor %}
        </ul>
      {% else %}
        <p>No topic created yet</p>
      {% endif %}
    </div>
  </div>
{% endblock %}